Processor Counter Monitor: ServerPCICFGUncore Class Reference
ServerPCICFGUncore Class Reference
Object to access uncore counters in a socket/processor with microarchitecture codename SandyBridge-EP (Jaketown) or Ivytown-EP or Ivytown-EX.
#include <cpucounters.h>
Public Types
enum EventPosition {
READ =0, WRITE =1, READ_RANK_A =0, WRITE_RANK_A =1,
READ_RANK_B =2, WRITE_RANK_B =3, PARTIAL =2, PMM_READ =2,
PMM_WRITE =3, PMM_MM_MISS_CLEAN =2, PMM_MM_MISS_DIRTY =3, NM_HIT =0,
M2M_CLOCKTICKS =1
}
Public Member Functions
ServerPCICFGUncore (uint32 socket_, const PCM *pcm)
Initialize access data structures.
void program ()
Program performance counters (disables programming power counters)
uint64 getImcReads ()
Get the number of integrated controller reads (in cache lines)
uint64 getImcReadsForController (uint32 controller)
Get the number of integrated controller reads for given controller (in cache lines)
uint64 getImcReadsForChannels (uint32 beginChannel, uint32 endChannel)
Get the number of integrated controller reads for given channels (in cache lines)
uint64 getImcWrites ()
Get the number of integrated controller writes (in cache lines)
uint64 getHALocalRequests ()
Get the number of requests to home agent (BDX/HSX only)
uint64 getHARequests ()
Get the number of local requests to home agent (BDX/HSX only)
uint64 getPMMReads ()
Get the number of PMM memory reads (in cache lines)
uint64 getPMMWrites ()
Get the number of PMM memory writes (in cache lines)
uint64 getEdcReads ()
Get the number of cache lines read by EDC (embedded DRAM controller)
uint64 getEdcWrites ()
Get the number of cache lines written by EDC (embedded DRAM controller)
uint64 getIncomingDataFlits (uint32 port)
Get the number of incoming data flits to the socket through a port.
uint64 getOutgoingFlits (uint32 port)
Get the number of outgoing data and non-data or idle flits (depending on the architecture) from the socket through a port.
void program_power_metrics (int mc_profile)
Program power counters (disables programming performance counters)
void programServerUncoreMemoryMetrics (const int rankA=-1, const int rankB=-1, const bool PMM=false, const bool PMMMixedMode=false)
Program memory counters (disables programming performance counters)
uint64 getQPIClocks (uint32 port)
Get number of QPI LL clocks on a QPI port.
uint64 getQPIL0pTxCycles (uint32 port)
Get number cycles on a QPI port when the link was in a power saving half-lane mode.
uint64 getUPIL0TxCycles (uint32 port)
Get number cycles on a UPI port when the link was in a L0 mode (fully active)
uint64 getQPIL1Cycles (uint32 port)
Get number cycles on a QPI port when the link was in a power saving shutdown mode.
uint64 getDRAMClocks (uint32 channel)
Get number DRAM channel cycles.
uint64 getMCDRAMClocks (uint32 channel)
Get number MCDRAM channel cycles.
uint64 getMCCounter (uint32 channel, uint32 counter)
Direct read of memory controller PMU counter (counter meaning depends on the programming: power/performance/etc)
uint64 getEDCCounter (uint32 channel, uint32 counter)
Direct read of embedded DRAM memory controller PMU counter (counter meaning depends on the programming: power/performance/etc)
uint64 getQPILLCounter (uint32 port, uint32 counter)
Direct read of QPI LL PMU counter (counter meaning depends on the programming: power/performance/etc)
uint64 getM2MCounter (uint32 box, uint32 counter)
Direct read of M2M counter.
void freezeCounters ()
Freezes event counting.
void unfreezeCounters ()
Unfreezes event counting.
uint64 computeQPISpeed (const uint32 ref_core, const int cpumodel)
Measures/computes the maximum theoretical QPI link bandwidth speed in GByte/seconds.
void enableJKTWorkaround (bool enable)
Enable correct counting of various LLC events (with memory access perf penalty)
size_t getNumQPIPorts () const
Returns the number of detected QPI ports.
uint64 getQPILinkSpeed (const uint32 linkNr) const
Returns the speed of the QPI link.
void reportQPISpeed () const
Print QPI Speeds.
uint32 getNumMC () const
Returns the number of detected integrated memory controllers.
size_t getNumMCChannels () const
Returns the total number of detected memory channels on all integrated memory controllers.
size_t getNumMCChannels (const uint32 controller) const
Returns the total number of detected memory channels on given integrated memory controller.
size_t getNumEDCChannels () const
Returns the total number of detected memory channels on all embedded DRAM controllers (EDC)
Friends
class PCM
Detailed Description
Object to access uncore counters in a socket/processor with microarchitecture codename SandyBridge-EP (Jaketown) or Ivytown-EP or Ivytown-EX.
Constructor & Destructor Documentation
ServerPCICFGUncore()
ServerPCICFGUncore::ServerPCICFGUncore (uint32 socket_, const PCM * pcm)
Initialize access data structures.
Parameters
socket_ socket id
pcm pointer to PCM instance
References getNumMC(), getNumMCChannels(), getNumQPIPorts(), and PCM::useLinuxPerfForUncore().
Member Function Documentation
getDRAMClocks()
uint64 ServerPCICFGUncore::getDRAMClocks (uint32 channel)
Get number DRAM channel cycles.
Parameters
channel channel number
getEDCCounter()
uint64 ServerPCICFGUncore::getEDCCounter (uint32 channel, uint32 counter)
Direct read of embedded DRAM memory controller PMU counter (counter meaning depends on the programming: power/performance/etc)
Parameters
channel channel number
counter counter number
getImcReadsForChannels()
uint64 ServerPCICFGUncore::getImcReadsForChannels (uint32 beginChannel, uint32 endChannel)
Get the number of integrated controller reads for given channels (in cache lines)
Parameters
beginChannel first channel in the range
endChannel last channel + 1: the range is [beginChannel, endChannel). endChannel is not included.
References getMCCounter().
Referenced by getImcReads(), and getImcReadsForController().
getImcReadsForController()
uint64 ServerPCICFGUncore::getImcReadsForController (uint32 controller)
Get the number of integrated controller reads for given controller (in cache lines)
Parameters
controller controller ID/number
References getImcReadsForChannels().
getIncomingDataFlits()
uint64 ServerPCICFGUncore::getIncomingDataFlits (uint32 port)
Get the number of incoming data flits to the socket through a port.
Parameters
port QPI port id
getM2MCounter()
uint64 ServerPCICFGUncore::getM2MCounter (uint32 box, uint32 counter)
Direct read of M2M counter.
Parameters
box box ID/number
counter counter number
getMCCounter()
uint64 ServerPCICFGUncore::getMCCounter (uint32 channel, uint32 counter)
Direct read of memory controller PMU counter (counter meaning depends on the programming: power/performance/etc)
Parameters
channel channel number
counter counter number
Referenced by getImcReadsForChannels().
getMCDRAMClocks()
uint64 ServerPCICFGUncore::getMCDRAMClocks (uint32 channel)
Get number MCDRAM channel cycles.
Parameters
channel channel number
getNumMCChannels()
size_t ServerPCICFGUncore::getNumMCChannels (const uint32 controller) const
Returns the total number of detected memory channels on given integrated memory controller.
Parameters
controller controller number
getOutgoingFlits()
uint64 ServerPCICFGUncore::getOutgoingFlits (uint32 port)
Get the number of outgoing data and non-data or idle flits (depending on the architecture) from the socket through a port.
Parameters
port QPI port id
References getQPILLCounter().
getQPIClocks()
uint64 ServerPCICFGUncore::getQPIClocks (uint32 port)
Get number of QPI LL clocks on a QPI port.
Parameters
port QPI port number
References getQPILLCounter().
getQPIL0pTxCycles()
uint64 ServerPCICFGUncore::getQPIL0pTxCycles (uint32 port)
Get number cycles on a QPI port when the link was in a power saving half-lane mode.
Parameters
port QPI port number
References getQPILLCounter().
getQPIL1Cycles()
uint64 ServerPCICFGUncore::getQPIL1Cycles (uint32 port)
Get number cycles on a QPI port when the link was in a power saving shutdown mode.
Parameters
port QPI port number
References getQPILLCounter().
getQPILLCounter()
uint64 ServerPCICFGUncore::getQPILLCounter (uint32 port, uint32 counter)
Direct read of QPI LL PMU counter (counter meaning depends on the programming: power/performance/etc)
Parameters
port port number
counter counter number
Referenced by getOutgoingFlits(), getQPIClocks(), getQPIL0pTxCycles(), getQPIL1Cycles(), and getUPIL0TxCycles().
getUPIL0TxCycles()
uint64 ServerPCICFGUncore::getUPIL0TxCycles (uint32 port)
Get number cycles on a UPI port when the link was in a L0 mode (fully active)
Parameters
port UPI port number
References getQPILLCounter().
program_power_metrics()
void ServerPCICFGUncore::program_power_metrics (int mc_profile)
Program power counters (disables programming performance counters)
Parameters
mc_profile memory controller measurement profile. See description of profiles in pcm-power.cpp
programServerUncoreMemoryMetrics()
void ServerPCICFGUncore::programServerUncoreMemoryMetrics (const int rankA = -1, const int rankB = -1, const bool PMM = false, const bool PMMMixedMode = false)
Program memory counters (disables programming performance counters)
Parameters
rankA count DIMM rank1 statistics (disables memory channel monitoring)
rankB count DIMM rank2 statistics (disables memory channel monitoring)
PMM monitor PMM bandwidth instead of partial writes
Program events for PMM mixed mode (AppDirect + MemoryMode)
References PCM::getInstance().
The documentation for this class was generated from the following files:
cpucounters.h
cpucounters.cpp