Processor Counter Monitor: cpucounters.h File Reference
cpucounters.h File Reference
Main CPU counters header.
#include "types.h"
#include "msr.h"
#include "pci.h"
#include "client_bw.h"
#include "width_extender.h"
#include "exceptions/unsupported_processor_exception.hpp"
#include <vector>
#include <array>
#include <limits>
#include <string>
#include <memory>
#include <map>
#include <string.h>
#include <semaphore.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <sys/syscall.h>
#include <unistd.h>
Classes
struct TopologyEntry
class HWRegister
class PCICFGRegister64
class PCICFGRegister32
class MMIORegister64
class MMIORegister32
class MSRRegister
class CounterWidthExtenderRegister
class UncorePMU
class ServerPCICFGUncore
Object to access uncore counters in a socket/processor with microarchitecture codename SandyBridge-EP (Jaketown) or Ivytown-EP or Ivytown-EX.
class SimpleCounterState
class PCM
CPU Performance Monitor.
struct PCM::SimplePCIeDevInfo
struct PCM::CustomCoreEventDescription
Custom Core event description.
struct PCM::ExtendedCustomCoreEventDescription
Extended custom core event description.
struct PCM::CustomIIOEventDescription
class BasicCounterState
Basic core counter state.
class UncoreCounterState
Basic uncore counter state.
class ServerUncoreCounterState
Server uncore power counter state.
class CoreCounterState
(Logical) core-wide counter state
class SocketCounterState
Socket-wide counter state.
class SystemCounterState
System-wide counter state.
Macros
#define PCM_VERSION " ($Format:%ci ID=%h$)"
#define PCM_API
#define NOMINMAX
#define PCM_GENERATE_METRIC_AVAILABLE_FUNCTION(m) bool is##m() const { return m; }
Typedefs
typedef SimpleCounterState PCIeCounterState
typedef SimpleCounterState IIOCounterState
typedef std::vector< uint64 > eventGroup_t
Functions
uint64 RDTSC ()
uint64 RDTSCP ()
template<class CounterStateType >
uint64 getQPIClocks (uint32 port, const CounterStateType &before, const CounterStateType &after)
Returns QPI LL clock ticks.
template<class CounterStateType >
int32 getThermalHeadroom (const CounterStateType &, const CounterStateType &after)
template<class CounterStateType >
uint64 getQPIL0pTxCycles (uint32 port, const CounterStateType &before, const CounterStateType &after)
Returns the number of QPI cycles in power saving half-lane mode.
template<class CounterStateType >
uint64 getQPIL1Cycles (uint32 port, const CounterStateType &before, const CounterStateType &after)
Returns the number of QPI cycles in power saving shutdown mode.
template<class CounterStateType >
double getNormalizedQPIL0pTxCycles (uint32 port, const CounterStateType &before, const CounterStateType &after)
Returns the ratio of QPI cycles in power saving half-lane mode.
template<class CounterStateType >
double getNormalizedQPIL1Cycles (uint32 port, const CounterStateType &before, const CounterStateType &after)
Returns the ratio of QPI cycles in power saving shutdown mode.
template<class CounterStateType >
uint64 getDRAMClocks (uint32 channel, const CounterStateType &before, const CounterStateType &after)
Returns DRAM clock ticks.
template<class CounterStateType >
uint64 getMCDRAMClocks (uint32 channel, const CounterStateType &before, const CounterStateType &after)
Returns MCDRAM clock ticks.
template<class CounterStateType >
uint64 getMCCounter (uint32 channel, uint32 counter, const CounterStateType &before, const CounterStateType &after)
Direct read of memory controller PMU counter (counter meaning depends on the programming: power/performance/etc)
template<class CounterStateType >
uint64 getM2MCounter (uint32 controller, uint32 counter, const CounterStateType &before, const CounterStateType &after)
Direct read of Memory2Mesh controller PMU counter (counter meaning depends on the programming: power/performance/etc)
template<class CounterStateType >
uint64 getEDCCounter (uint32 channel, uint32 counter, const CounterStateType &before, const CounterStateType &after)
Direct read of embedded DRAM memory controller counter (counter meaning depends on the programming: power/performance/etc)
template<class CounterStateType >
uint64 getPCUCounter (uint32 counter, const CounterStateType &before, const CounterStateType &after)
Direct read of power control unit PMU counter (counter meaning depends on the programming: power/performance/etc)
template<class CounterStateType >
uint64 getPCUClocks (const CounterStateType &before, const CounterStateType &after)
Returns clock ticks of power control unit.
template<class CounterStateType >
uint64 getConsumedEnergy (const CounterStateType &before, const CounterStateType &after)
Returns energy consumed by processor, excluding DRAM (measured in internal units)
template<class CounterStateType >
uint64 getDRAMConsumedEnergy (const CounterStateType &before, const CounterStateType &after)
Returns energy consumed by DRAM (measured in internal units)
template<class CounterStateType >
double getConsumedJoules (const CounterStateType &before, const CounterStateType &after)
Returns Joules consumed by processor (excluding DRAM)
template<class CounterStateType >
double getDRAMConsumedJoules (const CounterStateType &before, const CounterStateType &after)
Returns Joules consumed by DRAM.
PCM_API SystemCounterState getSystemCounterState ()
Reads the counter state of the system.
PCM_API SocketCounterState getSocketCounterState (uint32 socket)
Reads the counter state of a socket.
PCM_API CoreCounterState getCoreCounterState (uint32 core)
Reads the counter state of a (logical) core.
template<class CounterStateType >
double getIPC (const CounterStateType &before, const CounterStateType &after)
Computes average number of retired instructions per core cycle (IPC)
template<class CounterStateType >
uint64 getInstructionsRetired (const CounterStateType &before, const CounterStateType &after)
Computes the number of retired instructions.
template<class CounterStateType >
double getExecUsage (const CounterStateType &before, const CounterStateType &after)
Computes average number of retired instructions per time intervall.
template<class CounterStateType >
uint64 getInstructionsRetired (const CounterStateType &now)
Computes the number of retired instructions.
template<class CounterStateType >
uint64 getCycles (const CounterStateType &before, const CounterStateType &after)
Computes the number core clock cycles when signal on a specific core is running (not halted)
template<class CounterStateType >
uint64 getRefCycles (const CounterStateType &before, const CounterStateType &after)
Computes the number of reference clock cycles while clock signal on the core is running.
template<class CounterStateType >
uint64 getCycles (const CounterStateType &now)
Computes the number executed core clock cycles.
double getCoreIPC (const SystemCounterState &before, const SystemCounterState &after)
Computes average number of retired instructions per core cycle for the entire system combining instruction counts from logical cores to corresponding physical cores.
double getTotalExecUsage (const SystemCounterState &before, const SystemCounterState &after)
Computes average number of retired instructions per time intervall for the entire system combining instruction counts from logical cores to corresponding physical cores.
template<class CounterStateType >
double getAverageFrequency (const CounterStateType &before, const CounterStateType &after)
Computes average core frequency also taking Intel Turbo Boost technology into account.
template<class CounterStateType >
double getActiveAverageFrequency (const CounterStateType &before, const CounterStateType &after)
Computes average core frequency when not in powersaving C0-state (also taking Intel Turbo Boost technology into account)
template<class CounterStateType >
double getRelativeFrequency (const CounterStateType &before, const CounterStateType &after)
Computes average core frequency also taking Intel Turbo Boost technology into account.
template<class CounterStateType >
double getActiveRelativeFrequency (const CounterStateType &before, const CounterStateType &after)
Computes average core frequency when not in powersaving C0-state (also taking Intel Turbo Boost technology into account)
template<class CounterStateType >
double getL2CacheHitRatio (const CounterStateType &before, const CounterStateType &after)
Computes L2 cache hit ratio.
template<class CounterStateType >
double getL3CacheHitRatio (const CounterStateType &before, const CounterStateType &after)
Computes L3 cache hit ratio.
template<class CounterStateType >
uint64 getL3CacheMisses (const CounterStateType &before, const CounterStateType &after)
Computes number of L3 cache misses.
template<class CounterStateType >
uint64 getL2CacheMisses (const CounterStateType &before, const CounterStateType &after)
Computes number of L2 cache misses.
template<class CounterStateType >
uint64 getL2CacheHits (const CounterStateType &before, const CounterStateType &after)
Computes number of L2 cache hits.
template<class CounterStateType >
uint64 getL3CacheOccupancy (const CounterStateType &now)
Computes L3 Cache Occupancy.
template<class CounterStateType >
uint64 getLocalMemoryBW (const CounterStateType &before, const CounterStateType &after)
Computes Local Memory Bandwidth.
template<class CounterStateType >
uint64 getRemoteMemoryBW (const CounterStateType &before, const CounterStateType &after)
Computes Remote Memory Bandwidth.
template<class CounterStateType >
uint64 getL3CacheHitsNoSnoop (const CounterStateType &before, const CounterStateType &after)
Computes number of L3 cache hits where no snooping in sibling L2 caches had to be done.
template<class CounterStateType >
uint64 getL3CacheHitsSnoop (const CounterStateType &before, const CounterStateType &after)
Computes number of L3 cache hits where snooping in sibling L2 caches had to be done.
template<class CounterStateType >
uint64 getL3CacheHits (const CounterStateType &before, const CounterStateType &after)
Computes total number of L3 cache hits.
template<class CounterStateType >
uint64 getInvariantTSC (const CounterStateType &before, const CounterStateType &after)
Computes number of invariant time stamp counter ticks.
template<class CounterStateType >
double getCoreCStateResidency (int state, const CounterStateType &before, const CounterStateType &after)
Computes residency in the core C-state.
template<class CounterStateType >
uint64 getCoreCStateResidency (int state, const CounterStateType &now)
Reads raw residency counter for the core C-state.
template<class CounterStateType >
double getPackageCStateResidency (int state, const CounterStateType &before, const CounterStateType &after)
Computes residency in the package C-state.
template<class CounterStateType >
uint64 getPackageCStateResidency (int state, const CounterStateType &now)
Reads raw residency counter for the package C-state.
template<class CounterStateType >
uint64 getBytesReadFromMC (const CounterStateType &before, const CounterStateType &after)
Computes number of bytes read from DRAM memory controllers.
template<class CounterStateType >
uint64 getBytesWrittenToMC (const CounterStateType &before, const CounterStateType &after)
Computes number of bytes written to DRAM memory controllers.
template<class CounterStateType >
uint64 getBytesReadFromPMM (const CounterStateType &before, const CounterStateType &after)
Computes number of bytes read from PMM memory.
template<class CounterStateType >
uint64 getBytesWrittenToPMM (const CounterStateType &before, const CounterStateType &after)
Computes number of bytes written to PMM memory.
template<class CounterStateType >
uint64 getBytesReadFromEDC (const CounterStateType &before, const CounterStateType &after)
Computes number of bytes read from MCDRAM memory controllers.
template<class CounterStateType >
uint64 getBytesWrittenToEDC (const CounterStateType &before, const CounterStateType &after)
Computes number of bytes written to MCDRAM memory controllers.
template<class CounterStateType >
uint64 getIORequestBytesFromMC (const CounterStateType &before, const CounterStateType &after)
Computes number of bytes of read/write requests from all IO sources.
template<class CounterStateType >
uint64 getSMICount (const CounterStateType &before, const CounterStateType &after)
Returns the number of occured system management interrupts.
template<class CounterStateType >
uint64 getNumberOfCustomEvents (int32 eventCounterNr, const CounterStateType &before, const CounterStateType &after)
Returns the number of occured custom core events.
uint64 getIncomingQPILinkBytes (uint32 socketNr, uint32 linkNr, const SystemCounterState &before, const SystemCounterState &after)
Get estimation of QPI data traffic per incoming QPI link.
double getIncomingQPILinkUtilization (uint32 socketNr, uint32 linkNr, const SystemCounterState &before, const SystemCounterState &after)
Get data utilization of incoming QPI link (0..1)
double getOutgoingQPILinkUtilization (uint32 socketNr, uint32 linkNr, const SystemCounterState &before, const SystemCounterState &after)
Get utilization of outgoing QPI link (0..1)
uint64 getOutgoingQPILinkBytes (uint32 socketNr, uint32 linkNr, const SystemCounterState &before, const SystemCounterState &after)
Get estimation of QPI (data+nondata) traffic per outgoing QPI link.
uint64 getAllIncomingQPILinkBytes (const SystemCounterState &before, const SystemCounterState &after)
Get estimation of total QPI data traffic.
uint64 getAllOutgoingQPILinkBytes (const SystemCounterState &before, const SystemCounterState &after)
Get estimation of total QPI data+nondata traffic.
uint64 getIncomingQPILinkBytes (uint32 socketNr, uint32 linkNr, const SystemCounterState &now)
Return current value of the counter of QPI data traffic per incoming QPI link.
uint64 getSocketIncomingQPILinkBytes (uint32 socketNr, const SystemCounterState &now)
Get estimation of total QPI data traffic for this socket.
uint64 getAllIncomingQPILinkBytes (const SystemCounterState &now)
Get estimation of Socket QPI data traffic.
double getQPItoMCTrafficRatio (const SystemCounterState &before, const SystemCounterState &after)
Get QPI data to Memory Controller traffic ratio.
template<class CounterStateType >
double getLocalMemoryRequestRatio (const CounterStateType &before, const CounterStateType &after)
Get local memory access ration measured in home agent.
template<class CounterType >
uint64 getNumberOfEvents (const CounterType &before, const CounterType &after)
Returns the raw count of events.
template<class CounterStateType >
double getLLCReadMissLatency (const CounterStateType &before, const CounterStateType &after)
Returns average last level cache read+prefetch miss latency in ns.
Detailed Description
Main CPU counters header.
Include this header file if you want to access CPU counters (core and uncore - including memory controller chips and QPI)
Function Documentation
getActiveAverageFrequency()
template<class CounterStateType > double getActiveAverageFrequency (const CounterStateType & before, const CounterStateType & after)
Computes average core frequency when not in powersaving C0-state (also taking Intel Turbo Boost technology into account)
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
frequency in Hz
References PCM::getInstance(), and PCM::getNominalFrequency().
getActiveRelativeFrequency()
template<class CounterStateType > double getActiveRelativeFrequency (const CounterStateType & before, const CounterStateType & after)
Computes average core frequency when not in powersaving C0-state (also taking Intel Turbo Boost technology into account)
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
Fraction of nominal frequency (if >1.0 then Turbo was working during the measurement)
References PCM::getInstance().
getAllIncomingQPILinkBytes() [1/2]
uint64 getAllIncomingQPILinkBytes (const SystemCounterState & before, const SystemCounterState & after) inline
Get estimation of total QPI data traffic.
Returns an estimation of number of data bytes transferred to all sockets over all Intel(r) Quick Path Interconnect links
Parameters
before System CPU counter state before the experiment
after System CPU counter state after the experiment
Returns
Number of bytes
References PCM::getInstance(), and PCM::getNumSockets().
Referenced by getQPItoMCTrafficRatio().
getAllIncomingQPILinkBytes() [2/2]
uint64 getAllIncomingQPILinkBytes (const SystemCounterState & now) inline
Get estimation of Socket QPI data traffic.
Returns an estimation of number of data bytes transferred to all sockets over all Intel(r) Quick Path Interconnect links
Parameters
now System CPU counter state
Returns
Number of bytes
References PCM::getInstance(), PCM::getNumSockets(), and getSocketIncomingQPILinkBytes().
getAllOutgoingQPILinkBytes()
uint64 getAllOutgoingQPILinkBytes (const SystemCounterState & before, const SystemCounterState & after) inline
Get estimation of total QPI data+nondata traffic.
Returns an estimation of number of data and non-data bytes transferred from all sockets over all Intel(r) Quick Path Interconnect links
Parameters
before System CPU counter state before the experiment
after System CPU counter state after the experiment
Returns
Number of bytes
References PCM::getInstance(), and PCM::getNumSockets().
getAverageFrequency()
template<class CounterStateType > double getAverageFrequency (const CounterStateType & before, const CounterStateType & after)
Computes average core frequency also taking Intel Turbo Boost technology into account.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
frequency in Hz
References PCM::getInstance(), and PCM::getNominalFrequency().
getBytesReadFromEDC()
template<class CounterStateType > uint64 getBytesReadFromEDC (const CounterStateType & before, const CounterStateType & after)
Computes number of bytes read from MCDRAM memory controllers.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
Number of bytes
References PCM::getInstance().
getBytesReadFromMC()
template<class CounterStateType > uint64 getBytesReadFromMC (const CounterStateType & before, const CounterStateType & after)
Computes number of bytes read from DRAM memory controllers.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
Number of bytes
References PCM::getInstance().
Referenced by getQPItoMCTrafficRatio().
getBytesReadFromPMM()
template<class CounterStateType > uint64 getBytesReadFromPMM (const CounterStateType & before, const CounterStateType & after)
Computes number of bytes read from PMM memory.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
Number of bytes
References PCM::getInstance().
Referenced by getQPItoMCTrafficRatio().
getBytesWrittenToEDC()
template<class CounterStateType > uint64 getBytesWrittenToEDC (const CounterStateType & before, const CounterStateType & after)
Computes number of bytes written to MCDRAM memory controllers.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
Number of bytes
References PCM::getInstance().
getBytesWrittenToMC()
template<class CounterStateType > uint64 getBytesWrittenToMC (const CounterStateType & before, const CounterStateType & after)
Computes number of bytes written to DRAM memory controllers.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
Number of bytes
References PCM::getInstance().
Referenced by getQPItoMCTrafficRatio().
getBytesWrittenToPMM()
template<class CounterStateType > uint64 getBytesWrittenToPMM (const CounterStateType & before, const CounterStateType & after)
Computes number of bytes written to PMM memory.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
Number of bytes
References PCM::getInstance().
Referenced by getQPItoMCTrafficRatio().
getConsumedEnergy()
template<class CounterStateType > uint64 getConsumedEnergy (const CounterStateType & before, const CounterStateType & after)
Returns energy consumed by processor, excluding DRAM (measured in internal units)
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Referenced by getConsumedJoules().
getConsumedJoules()
template<class CounterStateType > double getConsumedJoules (const CounterStateType & before, const CounterStateType & after)
Returns Joules consumed by processor (excluding DRAM)
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
References getConsumedEnergy(), PCM::getInstance(), and PCM::getJoulesPerEnergyUnit().
getCoreCounterState()
PCM_API CoreCounterState getCoreCounterState (uint32 core)
Reads the counter state of a (logical) core.
Helper function. Uses PCM object to access counters.
Parameters
core core id
Returns
State of counters in the core
References PCM::getCoreCounterState(), and PCM::getInstance().
Referenced by PCM::getErrorMessage().
getCoreCStateResidency() [1/2]
template<class CounterStateType > double getCoreCStateResidency (int state, const CounterStateType & before, const CounterStateType & after) inline
Computes residency in the core C-state.
Parameters
state C-state
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
residence ratio (0..1): 0 - 0%, 1.0 - 100%
References PCM::getInstance(), getInvariantTSC(), getRefCycles(), and PCM::isCoreCStateResidencySupported().
getCoreCStateResidency() [2/2]
template<class CounterStateType > uint64 getCoreCStateResidency (int state, const CounterStateType & now) inline
Reads raw residency counter for the core C-state.
Parameters
state C-state #
now CPU counter state
Returns
raw residency value
getCoreIPC()
double getCoreIPC (const SystemCounterState & before, const SystemCounterState & after) inline
Computes average number of retired instructions per core cycle for the entire system combining instruction counts from logical cores to corresponding physical cores.
Use this metric to evaluate IPC improvement between SMT(Hyperthreading) on and SMT off.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
IPC
References PCM::getInstance(), getIPC(), PCM::getNumCores(), PCM::getNumOnlineCores(), and PCM::getThreadsPerCore().
getCycles() [1/2]
template<class CounterStateType > uint64 getCycles (const CounterStateType & before, const CounterStateType & after)
Computes the number core clock cycles when signal on a specific core is running (not halted)
Returns number of used cycles (halted cyles are not counted). The counter does not advance in the following conditions:
an ACPI C-state is other than C0 for normal operation
HLT
STPCLK+ pin is asserted
being throttled by TM1
during the frequency switching phase of a performance state transition
The performance counter for this event counts across performance state transitions using different core clock frequencies
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
number core clock cycles
getCycles() [2/2]
template<class CounterStateType > uint64 getCycles (const CounterStateType & now)
Computes the number executed core clock cycles.
Returns number of used cycles (halted cyles are not counted).
Parameters
now Current CPU counter state
Returns
number core clock cycles
getDRAMClocks()
template<class CounterStateType > uint64 getDRAMClocks (uint32 channel, const CounterStateType & before, const CounterStateType & after)
Returns DRAM clock ticks.
Parameters
channel DRAM channel number
before CPU counter state before the experiment
after CPU counter state after the experiment
getDRAMConsumedEnergy()
template<class CounterStateType > uint64 getDRAMConsumedEnergy (const CounterStateType & before, const CounterStateType & after)
Returns energy consumed by DRAM (measured in internal units)
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Referenced by getDRAMConsumedJoules().
getDRAMConsumedJoules()
template<class CounterStateType > double getDRAMConsumedJoules (const CounterStateType & before, const CounterStateType & after)
Returns Joules consumed by DRAM.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
References PCM::getCPUModel(), getDRAMConsumedEnergy(), PCM::getInstance(), and PCM::getJoulesPerEnergyUnit().
getEDCCounter()
template<class CounterStateType > uint64 getEDCCounter (uint32 channel, uint32 counter, const CounterStateType & before, const CounterStateType & after)
Direct read of embedded DRAM memory controller counter (counter meaning depends on the programming: power/performance/etc)
Parameters
counter counter number
channel channel number
before CPU counter state before the experiment
after CPU counter state after the experiment
References PCM::getInstance().
getExecUsage()
template<class CounterStateType > double getExecUsage (const CounterStateType & before, const CounterStateType & after)
Computes average number of retired instructions per time intervall.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
usage
Referenced by getTotalExecUsage().
getIncomingQPILinkBytes() [1/2]
uint64 getIncomingQPILinkBytes (uint32 socketNr, uint32 linkNr, const SystemCounterState & before, const SystemCounterState & after) inline
Get estimation of QPI data traffic per incoming QPI link.
Returns an estimation of number of data bytes transferred to a socket over Intel(r) Quick Path Interconnect
Parameters
socketNr socket identifier
linkNr linkNr
before System CPU counter state before the experiment
after System CPU counter state after the experiment
Returns
Number of bytes
References PCM::getInstance().
Referenced by getIncomingQPILinkUtilization().
getIncomingQPILinkBytes() [2/2]
uint64 getIncomingQPILinkBytes (uint32 socketNr, uint32 linkNr, const SystemCounterState & now) inline
Return current value of the counter of QPI data traffic per incoming QPI link.
Returns the number of incoming data bytes to a socket over Intel(r) Quick Path Interconnect
Parameters
socketNr socket identifier
linkNr linkNr
now Current System CPU counter state
Returns
Number of bytes
References PCM::getInstance().
getIncomingQPILinkUtilization()
double getIncomingQPILinkUtilization (uint32 socketNr, uint32 linkNr, const SystemCounterState & before, const SystemCounterState & after) inline
Get data utilization of incoming QPI link (0..1)
Returns an estimation of utilization of QPI link by data traffic transferred to a socket over Intel(r) Quick Path Interconnect
Parameters
socketNr socket identifier
linkNr linkNr
before System CPU counter state before the experiment
after System CPU counter state after the experiment
Returns
utilization (0..1)
References getIncomingQPILinkBytes(), PCM::getInstance(), getInvariantTSC(), PCM::getNominalFrequency(), PCM::getNumCores(), and PCM::getQPILinkSpeed().
getInstructionsRetired() [1/2]
template<class CounterStateType > uint64 getInstructionsRetired (const CounterStateType & before, const CounterStateType & after)
Computes the number of retired instructions.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
number of retired instructions
getInstructionsRetired() [2/2]
template<class CounterStateType > uint64 getInstructionsRetired (const CounterStateType & now)
Computes the number of retired instructions.
Parameters
now Current CPU counter state
Returns
number of retired instructions
getInvariantTSC()
template<class CounterStateType > uint64 getInvariantTSC (const CounterStateType & before, const CounterStateType & after)
Computes number of invariant time stamp counter ticks.
This counter counts irrespectively of C-, P- or T-states
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
number of time stamp counter ticks
Referenced by getCoreCStateResidency(), getIncomingQPILinkUtilization(), getLLCReadMissLatency(), getOutgoingQPILinkBytes(), getOutgoingQPILinkUtilization(), getPackageCStateResidency(), and PCM::getTickCount().
getIORequestBytesFromMC()
template<class CounterStateType > uint64 getIORequestBytesFromMC (const CounterStateType & before, const CounterStateType & after)
Computes number of bytes of read/write requests from all IO sources.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
Number of bytes
References PCM::getInstance().
getIPC()
template<class CounterStateType > double getIPC (const CounterStateType & before, const CounterStateType & after)
Computes average number of retired instructions per core cycle (IPC)
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
IPC
Referenced by getCoreIPC().
getL2CacheHitRatio()
template<class CounterStateType > double getL2CacheHitRatio (const CounterStateType & before, const CounterStateType & after)
Computes L2 cache hit ratio.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Warning
Works only in the DEFAULT_EVENTS programming mode (see program() method)
Returns
value between 0 and 1
References PCM::getInstance(), getL2CacheHits(), and getL2CacheMisses().
getL2CacheHits()
template<class CounterStateType > uint64 getL2CacheHits (const CounterStateType & before, const CounterStateType & after)
Computes number of L2 cache hits.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Warning
Works only in the DEFAULT_EVENTS programming mode (see program() method)
Returns
number of hits
References PCM::getInstance().
Referenced by getL2CacheHitRatio().
getL2CacheMisses()
template<class CounterStateType > uint64 getL2CacheMisses (const CounterStateType & before, const CounterStateType & after)
Computes number of L2 cache misses.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Warning
Works only in the DEFAULT_EVENTS programming mode (see program() method)
Returns
number of misses
References PCM::getInstance().
Referenced by getL2CacheHitRatio().
getL3CacheHitRatio()
template<class CounterStateType > double getL3CacheHitRatio (const CounterStateType & before, const CounterStateType & after)
Computes L3 cache hit ratio.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Warning
Works only in the DEFAULT_EVENTS programming mode (see program() method)
Returns
value between 0 and 1
References PCM::getInstance(), getL3CacheHits(), and getL3CacheMisses().
getL3CacheHits()
template<class CounterStateType > uint64 getL3CacheHits (const CounterStateType & before, const CounterStateType & after)
Computes total number of L3 cache hits.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Warning
Works only in the DEFAULT_EVENTS programming mode (see program() method)
Returns
number of hits
References PCM::getInstance(), getL3CacheHitsNoSnoop(), and getL3CacheHitsSnoop().
Referenced by getL3CacheHitRatio().
getL3CacheHitsNoSnoop()
template<class CounterStateType > uint64 getL3CacheHitsNoSnoop (const CounterStateType & before, const CounterStateType & after)
Computes number of L3 cache hits where no snooping in sibling L2 caches had to be done.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Warning
Works only in the DEFAULT_EVENTS programming mode (see program() method)
Returns
number of hits
References PCM::getInstance().
Referenced by getL3CacheHits().
getL3CacheHitsSnoop()
template<class CounterStateType > uint64 getL3CacheHitsSnoop (const CounterStateType & before, const CounterStateType & after)
Computes number of L3 cache hits where snooping in sibling L2 caches had to be done.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Warning
Works only in the DEFAULT_EVENTS programming mode (see program() method)
Returns
number of hits
References PCM::getInstance().
Referenced by getL3CacheHits().
getL3CacheMisses()
template<class CounterStateType > uint64 getL3CacheMisses (const CounterStateType & before, const CounterStateType & after)
Computes number of L3 cache misses.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Warning
Works only in the DEFAULT_EVENTS programming mode (see program() method)
Returns
number of misses
References PCM::getInstance().
Referenced by getL3CacheHitRatio().
getL3CacheOccupancy()
template<class CounterStateType > uint64 getL3CacheOccupancy (const CounterStateType & now)
Computes L3 Cache Occupancy.
References PCM::getInstance(), and PCM::L3CacheOccupancyMetricAvailable().
getLocalMemoryBW()
template<class CounterStateType > uint64 getLocalMemoryBW (const CounterStateType & before, const CounterStateType & after)
Computes Local Memory Bandwidth.
References PCM::CoreLocalMemoryBWMetricAvailable(), and PCM::getInstance().
Referenced by getRemoteMemoryBW().
getLocalMemoryRequestRatio()
template<class CounterStateType > double getLocalMemoryRequestRatio (const CounterStateType & before, const CounterStateType & after) inline
Get local memory access ration measured in home agent.
Parameters
before System CPU counter state before the experiment
after System CPU counter state after the experiment
Returns
Ratio
References PCM::getInstance().
getM2MCounter()
template<class CounterStateType > uint64 getM2MCounter (uint32 controller, uint32 counter, const CounterStateType & before, const CounterStateType & after)
Direct read of Memory2Mesh controller PMU counter (counter meaning depends on the programming: power/performance/etc)
Parameters
counter counter number
controller controller number
before CPU counter state before the experiment
after CPU counter state after the experiment
getMCCounter()
template<class CounterStateType > uint64 getMCCounter (uint32 channel, uint32 counter, const CounterStateType & before, const CounterStateType & after)
Direct read of memory controller PMU counter (counter meaning depends on the programming: power/performance/etc)
Parameters
counter counter number
channel channel number
before CPU counter state before the experiment
after CPU counter state after the experiment
getMCDRAMClocks()
template<class CounterStateType > uint64 getMCDRAMClocks (uint32 channel, const CounterStateType & before, const CounterStateType & after)
Returns MCDRAM clock ticks.
Parameters
channel MCDRAM channel number
before CPU counter state before the experiment
after CPU counter state after the experiment
getNormalizedQPIL0pTxCycles()
template<class CounterStateType > double getNormalizedQPIL0pTxCycles (uint32 port, const CounterStateType & before, const CounterStateType & after)
Returns the ratio of QPI cycles in power saving half-lane mode.
Parameters
port QPI port number
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
0..1 - ratio of QPI cycles in power saving half-lane mode
References getQPIClocks(), and getQPIL0pTxCycles().
getNormalizedQPIL1Cycles()
template<class CounterStateType > double getNormalizedQPIL1Cycles (uint32 port, const CounterStateType & before, const CounterStateType & after)
Returns the ratio of QPI cycles in power saving shutdown mode.
Parameters
port QPI port number
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
0..1 - ratio of QPI cycles in power saving shutdown mode
References getQPIClocks(), and getQPIL1Cycles().
getNumberOfCustomEvents()
template<class CounterStateType > uint64 getNumberOfCustomEvents (int32 eventCounterNr, const CounterStateType & before, const CounterStateType & after)
Returns the number of occured custom core events.
Read number of events programmed with the CUSTOM_CORE_EVENTS
Parameters
eventCounterNr Event/counter number (value from 0 to 3)
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
Number of bytes
getNumberOfEvents()
template<class CounterType > uint64 getNumberOfEvents (const CounterType & before, const CounterType & after) inline
Returns the raw count of events.
Parameters
before counter state before the experiment
after counter state after the experiment
getOutgoingQPILinkBytes()
uint64 getOutgoingQPILinkBytes (uint32 socketNr, uint32 linkNr, const SystemCounterState & before, const SystemCounterState & after) inline
Get estimation of QPI (data+nondata) traffic per outgoing QPI link.
Returns an estimation of number of data bytes transferred from a socket over Intel(r) Quick Path Interconnect
Parameters
socketNr socket identifier
linkNr linkNr
before System CPU counter state before the experiment
after System CPU counter state after the experiment
Returns
Number of bytes
References PCM::getInstance(), getInvariantTSC(), PCM::getNominalFrequency(), PCM::getNumCores(), getOutgoingQPILinkUtilization(), and PCM::getQPILinkSpeed().
getOutgoingQPILinkUtilization()
double getOutgoingQPILinkUtilization (uint32 socketNr, uint32 linkNr, const SystemCounterState & before, const SystemCounterState & after) inline
Get utilization of outgoing QPI link (0..1)
Returns an estimation of utilization of QPI link by (data+nondata) traffic transferred from a socket over Intel(r) Quick Path Interconnect
Parameters
socketNr socket identifier
linkNr linkNr
before System CPU counter state before the experiment
after System CPU counter state after the experiment
Returns
utilization (0..1)
References PCM::getInstance(), getInvariantTSC(), PCM::getNominalFrequency(), PCM::getNumCores(), and PCM::getQPILinkSpeed().
Referenced by getOutgoingQPILinkBytes().
getPackageCStateResidency() [1/2]
template<class CounterStateType > double getPackageCStateResidency (int state, const CounterStateType & before, const CounterStateType & after) inline
Computes residency in the package C-state.
Parameters
state C-state
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
residence ratio (0..1): 0 - 0%, 1.0 - 100%
References PCM::getInstance(), getInvariantTSC(), and PCM::isPackageCStateResidencySupported().
getPackageCStateResidency() [2/2]
template<class CounterStateType > uint64 getPackageCStateResidency (int state, const CounterStateType & now) inline
Reads raw residency counter for the package C-state.
Parameters
state C-state #
now CPU counter state
Returns
raw residency value
getPCUClocks()
template<class CounterStateType > uint64 getPCUClocks (const CounterStateType & before, const CounterStateType & after)
Returns clock ticks of power control unit.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
References getPCUCounter().
getPCUCounter()
template<class CounterStateType > uint64 getPCUCounter (uint32 counter, const CounterStateType & before, const CounterStateType & after)
Direct read of power control unit PMU counter (counter meaning depends on the programming: power/performance/etc)
Parameters
counter counter number
before CPU counter state before the experiment
after CPU counter state after the experiment
Referenced by getPCUClocks().
getQPIClocks()
template<class CounterStateType > uint64 getQPIClocks (uint32 port, const CounterStateType & before, const CounterStateType & after)
Returns QPI LL clock ticks.
Parameters
port QPI port number
before CPU counter state before the experiment
after CPU counter state after the experiment
Referenced by getNormalizedQPIL0pTxCycles(), and getNormalizedQPIL1Cycles().
getQPIL0pTxCycles()
template<class CounterStateType > uint64 getQPIL0pTxCycles (uint32 port, const CounterStateType & before, const CounterStateType & after)
Returns the number of QPI cycles in power saving half-lane mode.
Parameters
port QPI port number
before CPU counter state before the experiment
after CPU counter state after the experiment
Referenced by getNormalizedQPIL0pTxCycles().
getQPIL1Cycles()
template<class CounterStateType > uint64 getQPIL1Cycles (uint32 port, const CounterStateType & before, const CounterStateType & after)
Returns the number of QPI cycles in power saving shutdown mode.
Parameters
port QPI port number
before CPU counter state before the experiment
after CPU counter state after the experiment
Referenced by getNormalizedQPIL1Cycles().
getQPItoMCTrafficRatio()
double getQPItoMCTrafficRatio (const SystemCounterState & before, const SystemCounterState & after) inline
Get QPI data to Memory Controller traffic ratio.
Ideally for NUMA-optmized programs the ratio should be close to 0.
Parameters
before System CPU counter state before the experiment
after System CPU counter state after the experiment
Returns
Ratio
References getAllIncomingQPILinkBytes(), getBytesReadFromMC(), getBytesReadFromPMM(), getBytesWrittenToMC(), getBytesWrittenToPMM(), and PCM::getInstance().
getRefCycles()
template<class CounterStateType > uint64 getRefCycles (const CounterStateType & before, const CounterStateType & after)
Computes the number of reference clock cycles while clock signal on the core is running.
The reference clock operates at a fixed frequency, irrespective of core frequency changes due to performance state transitions. See Intel(r) Software Developer's Manual for more details
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
number core clock cycles
Referenced by getCoreCStateResidency().
getRelativeFrequency()
template<class CounterStateType > double getRelativeFrequency (const CounterStateType & before, const CounterStateType & after)
Computes average core frequency also taking Intel Turbo Boost technology into account.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
Fraction of nominal frequency
getRemoteMemoryBW()
template<class CounterStateType > uint64 getRemoteMemoryBW (const CounterStateType & before, const CounterStateType & after)
Computes Remote Memory Bandwidth.
References PCM::CoreRemoteMemoryBWMetricAvailable(), PCM::getInstance(), and getLocalMemoryBW().
getSMICount()
template<class CounterStateType > uint64 getSMICount (const CounterStateType & before, const CounterStateType & after)
Returns the number of occured system management interrupts.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
Number of SMIs (system manegement interrupts)
getSocketCounterState()
PCM_API SocketCounterState getSocketCounterState (uint32 socket)
Reads the counter state of a socket.
Helper function. Uses PCM object to access counters.
Parameters
socket socket id
Returns
State of counters in the socket
References PCM::getInstance(), and PCM::getSocketCounterState().
Referenced by PCM::getErrorMessage().
getSocketIncomingQPILinkBytes()
uint64 getSocketIncomingQPILinkBytes (uint32 socketNr, const SystemCounterState & now) inline
Get estimation of total QPI data traffic for this socket.
Returns an estimation of number of bytes transferred to this sockets over all Intel(r) Quick Path Interconnect links on this socket
Parameters
before System CPU counter state before the experiment
after System CPU counter state after the experiment
Returns
Number of bytes
References PCM::getInstance().
Referenced by getAllIncomingQPILinkBytes().
getSystemCounterState()
PCM_API SystemCounterState getSystemCounterState ()
Reads the counter state of the system.
Helper function. Uses PCM object to access counters.
System consists of several sockets (CPUs). Socket has a CPU in it. Socket (CPU) consists of several (logical) cores.
Returns
State of counters in the entire system
References PCM::getInstance(), and PCM::getSystemCounterState().
Referenced by PCM::getErrorMessage().
getTotalExecUsage()
double getTotalExecUsage (const SystemCounterState & before, const SystemCounterState & after) inline
Computes average number of retired instructions per time intervall for the entire system combining instruction counts from logical cores to corresponding physical cores.
Use this metric to evaluate cores utilization improvement between SMT(Hyperthreading) on and SMT off.
Parameters
before CPU counter state before the experiment
after CPU counter state after the experiment
Returns
usage
References getExecUsage(), PCM::getInstance(), PCM::getNumCores(), PCM::getNumOnlineCores(), and PCM::getThreadsPerCore().